########################################################################
# This workflow will deploy all app components to a specific environment
########################################################################
name: Deploy To Environment

on:
  workflow_call:
    inputs:
      environment:
        description: 'environment to deploy solution to'
        required: true
        type: string

  workflow_dispatch:
    inputs:
      environment:
        description: 'environment to deploy solution to'
        required: true
        type: environment
        
permissions:
  id-token: write
  contents: read
  
#######################################################################
# Need to call deploy-powerapp-solution.yml for each solution so we   #
# pass in the settings for each solution.  Have not found a way to    #
# programatically select a variable for use.                           #
#######################################################################

jobs:
  variablesetup:
    environment: ${{ github.event.inputs.environment}}
    runs-on: windows-latest
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment}}
      ALMLAB_SETTINGS_FILE: ${{vars.ALMLAB_SETTINGSFILE}}
      GITHUB_SETTINGS_FILE: ${{vars.XGITHUB_SETTINGSFILE}}
    
    steps:
      - run: |
          write-host environment ${{ env.ENVIRONMENT }}
        shell: pwsh

  ALMLAB-call-powerapp-solution-deployment:
     uses: ./.github/workflows/deploy-powerapp-solution.yml
     with:
       environment: ${{ inputs.environment }}
       settingsfilecontents: "HardCoded-fix!"
       solutionName: "GITHUB"
     secrets: inherit
  
  variableread:
    runs-on: windows-latest
    needs: variablesetup

    steps:
      - run: |
          write-host environment ${{ env.ENVIRONMENT }}
          write-host almlab settings ${{ env.ALMLAB_SETTINGS_FILE }}
          write-host github settings ${{ env.GITHUB_SETTINGS_FILE }}
        shell: pwsh

  #GITHUB-call-powerapp-solution-deployment: 
  #  uses: ./.github/workflows/deploy-powerapp-solution.yml
  #  with:
  #    environment: ${{ inputs.environment }}
  #    settingsfilecontents: ${{env.GITHUB_SETTINGSFILE}}
  #    solutionName: "GITHUB"
  #  secrets: inherit
    
  ################################################  
  # Use this template to call reusable workflows #
  # to deploy other parts of the app             #
  ################################################
  #SomeOtherComponent-Call-somethingelse-deployment
  #  uses: ./.github/workflows/component-deployment.yml
  #  with:
  #    environment: ${{ inputs.environment }}
  #    <other variables to pass>
  #  secrets: inherit
