########################################################################
# This workflow will deploy all app components to a specific environment
########################################################################
name: Deploy To Environment

on:
  workflow_call:
    inputs:
      environment:
        description: 'environment to deploy solution to'
        required: true
        type: string

  workflow_dispatch:
    inputs:
      environment:
        description: 'environment to deploy solution to'
        required: true
        type: environment
        
permissions:
  id-token: write
  contents: read
  
#######################################################################
# Need to call deploy-powerapp-solution.yml for each solution so we   #
# pass in the settings for each solution.  Have not found a way to    #
# programatically select a variable for use.                           #
#######################################################################
jobs:
  ALMLAB-call-powerapp-solution-deployment:
     uses: ./.github/workflows/deploy-powerapp-solution.yml
     with:
       environment: ${{ inputs.environment }}
       settingsfilecontents: ${{ vars.ALMLab_SETTINGSFILE }}
       solutionName: "ALMLAB"
     secrets: inherit
  
  ##############################################
  # NOTE: PowerPlat doesn't like importing two #
  # solutions at the same time from the same   #
  # account.  Added 'needs' statement          #
  ##############################################
  GITHUB-call-powerapp-solution-deployment: 
    uses: ./.github/workflows/deploy-powerapp-solution.yml
    needs: ALMLAB-call-powerapp-solution-deployment
    with:
      environment: ${{ inputs.environment }}
      settingsfilecontents: ${{ vars.XGITHUB_SETTINGS_FILE }}
      solutionName: "GITHUB"
    secrets: inherit
  
  ################################################  
  # Use this template to call reusable workflows #
  # to deploy other parts of the app             #
  ################################################
  APPX-call-prodev-solution-deployment:
    uses: ./.github/workflows/deploy-prodev-solution.yml
    with:
      environment: ${{ inputs.environment }}
      #othervariabletopass: ${{needs.variablesetup.outputs.othervariabletopass}}
    secrets: inherit
  


