# This is a basic workflow to help you get started with Actions

name: matrixtest

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        default: 'Dev'
        
      testvar:
        type: string
        default: '["ALMLAB","GITHUB"]' #setting up the JSON array for the matrix
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  example_matrix:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    strategy:
      matrix:
         value: ${{fromJson(inputs.testvar)}} #Need to pass in a JSON Array
         
   # env:
    #  DynamicRef: ${{ vars.format('{0}_SETTINGSFILE','ALMLAB') }}
    
    steps:
      - uses: kanga333/variable-mapper@master
        with:
          key: "${{matrix.value}}"
          map : |
            {
              "ALMLAB":{"SettingsFile":"${{vars.ALMLAB_SETTINGSFILE}}"},
              "GITHUB:{"SettingsFile":"${{vars.XGITHUB_SETTINGSFILE}}"}
            }
    
      - run: |
          write-host "hello... ${{ matrix.value }}"
          write-host "Settings File - ${{env.SettingsFile}}"
        shell: pwsh
