# This is a basic workflow to help you get started with Actions

name: matrixtest

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        default: 'dev'
        
      testvar:
        type: string
        default: '["1","2","3"]' #setting up the JSON array for the matrix
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
         value: ${{fromJson(inputs.testvar)}} #Need to pass in a JSON Array
         
    env:
      DynamicRef: ${{ vars.format('{0}_SETTINGSFILE','ALMLAB') }}
    
    steps:
      - run: |
          write-host "hello... ${{ matrix.value }}"
          write-host "DynamicRef - ${{env.DynamicRef}}"
        shell: pwsh
