# This is a basic workflow to help you get started with Actions

name: matrixtest

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        default: 'Dev'
        
      testvar:
        type: string
        default: '["ALMLAB","GITHUB"]' #setting up the JSON array for the matrix
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  example_matrix:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    strategy:
      matrix:
         value: ${{fromJson(inputs.testvar)}} #Need to pass in a JSON Array
         
   # env:
    #  DynamicRef: ${{ vars.format('{0}_SETTINGSFILE','ALMLAB') }}
    
    steps:
      ##### This doesn't like a JSON result
      #- uses: kanga333/variable-mapper@master
      #  with:
      #    key: "${{matrix.value}}"
      #    map : |
      #      {
      #        "ALMLAB":{"SettingsFile":"${{vars.ALMLAB_SETTINGSFILE}}"},
      #        "GITHUB":{"SettingsFile":"${{vars.XGITHUB_SETTINGSFILE}}"}
      #      }
      
      ##### This appears to work but write-host is only showing one line
      #- uses: dkershner6/switch-case-action@v1
      #  id: switch-case
      #  with:
      #    default: "This is the default value"
      #    conditionals-with-values: |
      #      ${{ matrix.value == 'ALMLAB'}} => ${{vars.ALMLAB_SETTINGSFILE}}
      #      ${{ matrix.value == 'GITHUB'}} => ${{vars.XGITHUB_SETTINGSFILE}}
      
      - run: |
          $a = "${{ matrix.value }}"
          switch($a){
            "ALMLAB"{$s="${{vars.ALMLAB_SETTINGSFILE}}" | ConvertTo-Json}
            "GITHUB"{$s="${{vars.XGITHUB_SETTINGSFILE}}" | ConvertTo-Json}
          }
          write-host $s
        shell: pwsh
    
    
      - run: |
          write-host "hello... ${{ matrix.value }}"
          write-host "SomeTestVariable - ${{env.SomeTestVariable}}"
        shell: pwsh
