# This is a basic workflow to help you get started with Actions

name: PowerApp-Release-Solution-To-Environment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: 'environment to run on'
        required: true
env:
  SOLUTION_EXPORTED_FOLDER: out/exported/
  SOLUTION_FOLDER: out/solutions/
  SOLUTION_TARGET_FOLDER: powerPlatSolutions/
  SOLUTION_SHIPPING_FOLDER: out/ship

jobs:
  deploy:
    environment: ${{ github.event.inputs.environment }}
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
      
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          
      - name: check packed unmanaged solution
        uses: microsoft/powerplatform-actions/check-solution@v0
        with:
          environment-url: ${{vars.ENVIRONMENT_URL}}
          app-id: ${{vars.CLIENT_ID}}
          client-secret: ${{ secrets.PowerPlatformSPN }}
          tenant-id: ${{vars.TENANT_ID}}
          path: ${{ env.SOLUTION_TARGET_FOLDER}}/${{ vars.SOLUTION_NAME }}_artifacts/${{ vars.SOLUTION_NAME }}.zip
      
      - name: update settings file
        run: |
          dir
          dir .\${{ env.SOLUTION_TARGET_FOLDER}}/${{ vars.SOLUTION_NAME }}_artifacts
          $a = Get-Content '.\a${{ env.SOLUTION_TARGET_FOLDER}}/${{ vars.SOLUTION_NAME }}_artifacts/${{ vars.SOLUTION_NAME }}_SettingsFile.json' -raw | ConvertFrom-Json
          $a.EnvironmentVariables | ForEach-Object{if($_.SchemaName -eq 'almLab_TestEnvironmentVariable'){$_.Value = 'This is the test environment'}}
          $a | ConvertTo-Json -Depth 100 | Set-Content '.\Updated${{ vars.SOLUTION_NAME }}_SettingsFile.json'
          dir
          type .\testupdate.json
        shell: pwsh
      
      ###########################################################################################################
      # NOTE: If the environment variable doesn't have a value and only a default value, there will be no change
      #       When you actually have a value for the environment variable, a new json file is created when the
      #       solution is exported.  Seems that using the deployment settings file to update that value won't 
      #       work if you origionally didn't have a value / json file.
      ###########################################################################################################
      - name: import unmanaged solution
        uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: ${{vars.ENVIRONMENT_URL}}
          app-id: ${{vars.CLIENT_ID}}
          client-secret: ${{ secrets.PowerPlatformSPN }}
          tenant-id: ${{vars.TENANT_ID}}
          solution-file: ${{ env.SOLUTION_TARGET_FOLDER}}/${{ vars.SOLUTION_NAME }}_artifacts/${{ vars.SOLUTION_NAME }}.zip
          force-overwrite: true
          publish-changes: true
          deployment-settings-file: .\Updated${{ vars.SOLUTION_NAME }}_SettingsFile.json
          use-deployment-settings-file: true

