# This is a basic workflow to help you get started with Actions

name: PowerApp-Release-Solution-To-Matrix

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Deploy-to-Test-and-Prod:
    strategy:
      max-parallel: 1
      matrix:
        targetEnvironment: [Test, Prod]
        
    runs-on: windows-latest
    
    steps:    
      - uses: ./.github/workflows/PowerApp-Release-To-Environment.yml
        with: 
          environment: ${{matrix.targetEnvironment}}
          
      - run: |
          write-host environment: ${{matrix.targetEnvironment}}
        shell: pwsh
