# NOTE: Tried to use a Matrix Strategy, but the child workflows 
#       were not reading from the environment correctly

name: PowerApp-Release-Solution-To-All-Environments

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  Deploy-To-Test:
    uses: ./.github/workflows/PowerApp-Release-To-Environment.yml
    with:
      environment: Test
    secrets: inherit
    
  Deploy-To-Prod:
    needs: Deploy-To-Test     
    uses: ./.github/workflows/PowerApp-Release-To-Environment.yml
    with:
      environment: Prod
    secrets: inherit

