# This is a basic workflow to help you get started with Actions

name: Release Solution

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    environment: build
    runs-on: windows-latest
    env:
      # Emit debug information
      RUNNER_DEBUG: 1
      
      # Folder name for staging the exported solution
      SOLUTION_SHIPPING_FOLDER: out/ship/

      # Staging the unpacked solution folder before check-in
      SOLUTION_OUTBOUND_FOLDER: out/solutions/

      # Folder name to be created and checked in
      SOLUTION_SOURCE_FOLDER: solutions/

      # Folder where the relased binaries are going to be hosted
      SOLUTION_RELEASE_FOLDER: out/release

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          
      - name: See if things are where we want them
        run: |
          dir .\${{ env.SOLUTION_SOURCE_FOLDER }}/${{ vars.SOLUTION_NAME }}_artifacts/${{ vars.SOLUTION_NAME }}
        shell: pwsh
          
      - name: verify connection to power platform - hardcoded
        uses: microsoft/powerplatform-actions/who-am-i@v0
        with:
          environment-url: https://org89c5d0b2.crm.dynamics.com
          app-id: ebdcb7b1-8e92-4ae1-b144-fcadc6014b84
          client-secret: ${{ secrets.PowerPlatformSPN }}
          tenant-id: e2642959-067c-4ff5-ba76-d4cf80a4f58f    
          
      - name: verify connection to power platform
        uses: microsoft/powerplatform-actions/who-am-i@v0
        with:
          environment-url: ${{vars.ENVIRONMENT_URL}}
          app-id: ${{vars.CLIENT_ID}}
          client-secret: ${{ secrets.PowerPlatformSPN }}
          tenant-id: ${{vars.TENANT_ID}}
      
      - name: pack unmanaged solution
        uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-folder: ${{ env.SOLUTION_SOURCE_FOLDER }}/${{ vars.SOLUTION_NAME }}_artifacts/${{ vars.SOLUTION_NAME }}
          solution-file: ${{ env.SOLUTION_OUTBOUND_FOLDER }}/${{ vars.SOLUTION_NAME }}_artifacts/${{ vars.SOLUTION_NAME }}.zip
          solution-type: Unmanaged
      
      - name: import solution to build environment
        run: echo importing unmanaged solution to build environment
      
      - name: export managed solution
        run: echo exporting managed solution
      
      - name: check exported solution
        run: echo checking consistency of managed solution
      
      - name: create release artifacts
        run: echo creating release artifacts
      
      - name: cleanup build environment
        run: echo cleaning up build environment
        
  deploy-to-test:
    environment: test
    needs: build
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
      
    steps:
      - uses: actions/checkout@v3
      
      - name: fetch unmanaged solution from artifacts
        run: echo fetching unmanaged solution from release artifacts
      
      - name: update settings file
        run: echo updating settings file for environment
      
      - name: import unmanaged solution
        run: echo importing unmanaged solution

  deploy-to-prod:
    environment: prod
    needs: deploy-to-test
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
      
    steps:
      - uses: actions/checkout@v3
      
      - name: fetch managed solution from artifacts
        run: echo fetring managed solution from release artifacts
      
      - name: update settings file
        run: echo updating settings file for environment
      
      - name: import managed solution
        run: echo importing unmanaged solution
