# This is a basic workflow to help you get started with Actions

name: Release Solution

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    environment: build
    # The type of runner that the job will run on
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
      - name: pack unmanaged solution
        run: echo packing unmanaged solution
      
      - name: import solution to build environment
        run: echo importing unmanaged solution to build environment
      
      - name: export managed solution
        run: echo exporting managed solution
      
      - name: check exported solution
        run: echo checking consistency of managed solution
      
      - name: create release artifacts
        run: echo creating release artifacts
      
      - name: cleanup build environment
        run: echo cleaning up build environment
        
  deploy-to-test:
    environment: test
    needs: build
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
      
    steps:
      - uses: actions/checkout@v3
      
      - name: fetch unmanaged solution from artifacts
        run: echo fetching unmanaged solution from release artifacts
      
      - name: update settings file
        run: echo updating settings file for environment
      
      - name: import unmanaged solution
        run: echo importing unmanaged solution

  deploy-to-prod:
    environment: prod
    needs: deploy-to-test
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
      
    steps:
      - uses: actions/checkout@v3
      
      - name: fetch managed solution from artifacts
        run: echo fetring managed solution from release artifacts
      
      - name: update settings file
        run: echo updating settings file for environment
      
      - name: import managed solution
        run: echo importing unmanaged solution
