name: Release

on:
  workflow_dispatch:

jobs:
  deployment_matrix:
    strategy:
      matrix:
         environment: ["Test","Prod"]
    uses: ./.github/workflows/deploy-to-environment.yml
    with:
      environment: ${{ matrix.environment }}
    
    
